GenerateNU/arenius

CONTRIBUTING.md
README.md

adds CONTRIBUTING.md and some general repo information
_more detailed backend info coming soon_

feat: init docs

---

.github/workflows/backend.yaml
backend/cmd/main.go
backend/go.mod
backend/internal/models/transaction.go
backend/internal/service/handler/transaction/create_transaction.go
backend/internal/service/handler/transaction/handler.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/transaction.go
backend/internal/storage/postgres/storage.go
backend/internal/storage/storage.go

this PR connects our Supabase DB and creates a sample endpoint with the handler structure we'll be using. right now the endpoint just returns whatever you give it, but a potential task for bootcamp tomorrow could be storing it in the DB :)
(it also updates the backend CI .yaml file since I noticed it wasn't running properly — I removed the format step since it wasn't working and even if it was, I don't think it would've had an effect since we didn't push the formatted results to the branch. assuming we could add that later if we wanted to though)

Connect DB and write sample endpoint

---

backend/internal/storage/postgres/schema/transaction.go

[Link to Ticket](https://github.com/orgs/GenerateNU/projects/41?pane=issue&itemId=93376335&issue=GenerateNU%7Carenius%7C9)
Ran locally with success and error cases
Closes https://github.com/orgs/GenerateNU/projects/41?pane=issue&itemId=93376335&issue=GenerateNU%7Carenius%7C9

Add SQL query for posting transactions

---

backend/internal/models/line_item.go
backend/internal/service/handler/lineitem/reconcile_lineitem.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/line_item.go
backend/internal/storage/storage.go

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/13)
Added PATCH method that updates an item in the LineItem table with a new emission factor, amount and unit. 
Postman requests, see screenshots. 
http://127.0.0.1:8080/line-item/1
{
"emission_factor": "factor_UPDATE", 
"amount": 69,
"unit": "gigabytes"
}

Reconcile lineitem with emission factor, unit and amount 

---

backend/internal/models/line_item.go
backend/internal/service/handler/lineitem/post_line_items.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/line_item.go
backend/internal/storage/storage.go

[BE-18](https://github.com/GenerateNU/arenius/issues/18)
Added a POST endpoint for line items with the following request schema:
```
type CreateLineItemRequest struct {
Description    string   `json:"description"`
Quantity       float64  `json:"quantity"`
UnitAmount     float64  `json:"unit_amount"`
CompanyID      string   `json:"company_id"`
ContactID      string   `json:"contact_id"`
EmissionFactor *string  `json:"emission_factor,omitempty"`
Amount         *float64 `json:"amount,omitempty"`
Unit           *string  `json:"unit,omitempty"`
CO2            *float64 `json:"co2,omitempty"`
Scope          *int     `json:"scope,omitempty"`
CO2Unit        *string  `json:"co2_unit,omitempty"`
}
```
*type indicates an optional parameter. Note that CompanyID is a UUID foreign key to the company …

Be 18 line item post

---

backend/README.md
backend/internal/README.md
backend/internal/models/emissions_factor.go
backend/internal/models/line_item.go
backend/internal/service/climatiq/batch_estimate.go
backend/internal/service/climatiq/search.go
backend/internal/service/handler/carbon/search_factors.go
backend/internal/service/handler/emissionsFactor/handler.go
backend/internal/service/handler/emissionsFactor/populate_emissions.go
backend/internal/service/handler/lineitem/estimate_carbon.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/emissions_factor.go
backend/internal/storage/postgres/schema/line_item.go
backend/internal/storage/storage.go
backend/internal/supabase/migrations/20250121032400_create_emissions.sql
backend/internal/supabase/migrations/20250124034258_drop_transactions.sql
backend/internal/supabase/seed.sql
frontend/package.json
frontend/render.yaml

Create Line Item Form

---

backend/internal/models/line_item.go
backend/internal/storage/postgres/schema/line_item.go
frontend/package-lock.json
frontend/package.json
frontend/src/app/dashboard/page.tsx
frontend/src/components/dashboard/ItemForm.tsx
frontend/src/components/dashboard/ItemRow.tsx
frontend/src/components/dashboard/ItemTable.tsx
frontend/src/services/apiClient.ts
frontend/src/services/dashboard.ts
frontend/src/types.ts

[Link to Ticket](https://github.com/orgs/GenerateNU/projects/41/views/1?pane=issue&itemId=94674137&issue=GenerateNU%7Carenius%7C22)
Added a simple frontend form that creates a line item
http://localhost:3000/dashboard
Closes #22

Frontend Line Item Form

---

backend/internal/models/line_item.go
backend/internal/storage/postgres/schema/line_item.go
frontend/src/app/dashboard/page.tsx
frontend/src/components/dashboard/ItemForm.tsx
frontend/src/components/dashboard/ItemRow.tsx
frontend/src/components/dashboard/ItemTable.tsx
frontend/src/types.ts

This updates the line items page to include the name of an emissions factor along with other relevant line item fields. It also reformats the manual entry form to be horizontal and take up less space.
localhost:8080/line-item
http://localhost:3000/dashboard

Update line items screen

---

backend/internal/README.md

Update README For Summaries Endpoint

---

backend/internal/README.md
backend/internal/service/handler/lineItem/batch_update_scope_emissions.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/line_item.go
backend/internal/storage/storage.go

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/65#issue-2843808252)
Added batch enpoint to update scope and emissions factor of 1+ line items
localhost:8080/line-item/batch
scope and emissions factor are optional
{
"line_item_ids": ["02d8571d-587a-48aa-ad04-e40d883ff791", "0399deaf-1f33-4d92-b2ca-33f57356d5b5", "0436e718-c205-4444-9fce-d07c5f9823cc"],
"emissions_factor_id": "machinery-type_rolling_mill_and_other_metalworking_machinery",
"scope": 2
}

Batch Line Item Update

---

backend/internal/README.md
backend/internal/models/line_item.go
backend/internal/storage/postgres/schema/line_item.go

[Link to Ticket](64)
Added a new query parameter, SearchTerm that matches with line item descriptions, case insensitive.
[
](url)
Closes #64

adding search term for description line item GET

---

backend/internal/service/handler/xero/get_bank_transactions.go

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/76)
If an imported transaction doesn't have a line item description, it will make one out of the transaction type and the contact name. Both transaction type and contact name are required on BankTransaction POST for Xero, so they should be there.
The transaction I pulled in:
The resulting record in supabase:
Closes #76

Making default description for line item type + contact

---

backend/internal/service/handler/xero/xero_middleware.go
backend/internal/service/server.go

signup fix

---

backend/internal/README.md
backend/internal/models/company_favorites.go
backend/internal/service/handler/emissionsFactor/get_all_emissions.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/emissions_factor.go
backend/internal/storage/storage.go
backend/internal/supabase/migrations/20250226222551_create_company_favorites.sql

Added favorites
[Link to Ticket](https://github.com/GenerateNU/arenius/issues/104)
Closes #104

BE: Add Favorites Tab #104

---

backend/internal/storage/postgres/schema/emissions_factor.go

For Dessy Part 2

---

backend/internal/README.md
backend/internal/models/contact.go
backend/internal/service/handler/contact/get_contact.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/contact.go
backend/internal/storage/storage.go

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/107)
I ascended
http://localhost:8080/contact/b8c4b3e2-08f1-45e9-94a0-125a7e73b4d6
Closes #107

BE: Get individual contact endpoint #107

---

backend/internal/models/contact.go
backend/internal/service/handler/contact/get_contacts.go
backend/internal/service/handler/lineItem/get_line_items.go
backend/internal/storage/postgres/schema/contact.go
backend/internal/storage/storage.go
frontend/src/app/(main)/contacts/page.tsx
frontend/src/components/contacts/ContactForm.tsx
frontend/src/services/contacts.ts
frontend/src/types.ts

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/97)
Made the contacts page cooler
https://github.com/user-attachments/assets/ce729767-7b11-43bb-9628-c84838708103
https://github.com/user-attachments/assets/0d493975-8d2c-4a75-9f1b-a9c6802afd63
Closes #97

BE/FE: Contacts page improvements #97

---

backend/internal/service/handler/auth/login.go
backend/internal/service/handler/xero/redirect_to_xero.go
backend/internal/service/handler/xero/sync_company_transactions.go
backend/internal/service/handler/xero/sync_transactions.go
backend/internal/storage/postgres/schema/line_item.go
frontend/src/context/AuthContext.tsx

Some sync fixes

---

backend/internal/service/handler/xero/redirect_to_xero.go
frontend/src/context/AuthContext.tsx
frontend/src/context/Context.tsx
frontend/src/services/lineItems.ts

Moved setting frontend auth stuff to be watching for the completion of xeor redirect so that on signup, line items are synced

signup cookies logic fixed

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/(main)/contacts/page.tsx
frontend/src/app/(main)/transactions/page.tsx
frontend/src/hooks/useDebouncedSearch.ts

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/132)
https://github.com/user-attachments/assets/21dcf572-a5a3-4e9d-a5f5-d42fd1d9de8c
Closes #132

Debouncing

---

backend/internal/service/handler/summary/get_gross_summary.go
backend/internal/service/handler/summary/get_net_summary.go
backend/internal/service/server.go

Move Some Shit Around

---

backend/internal/README.md
backend/internal/models/carbon_offset.go
backend/internal/models/line_item.go
backend/internal/service/handler/carbonOffset/batch_create_carbon_offsets.go
backend/internal/service/handler/carbonOffset/post_carbon_offset.go
backend/internal/service/handler/lineItem/batch_update_scope_emissions.go
backend/internal/service/server.go
backend/internal/storage/postgres/schema/carbon_offset.go
backend/internal/storage/storage.go

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/148)
We decided to change the scope of this ticket. Instead of batch reconciles leading to creating multiple carbon offsets, we made a new batch endpoint for creating carbon offsets
Closes #148

Fix Some batch reconcile Shit

---

frontend/src/components/onboarding/login-form.tsx

https://github.com/user-attachments/assets/db06073e-a3a9-4341-95fb-3d58d62d17c2

Loading Button

---

backend/internal/storage/postgres/schema/summary.go
frontend/src/components/dashboard/TopEmissions.tsx

Fix Dashboard For No Data

---

frontend/src/components/contacts/ContactForm.tsx

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/232)
Itty bitty ticket to restyle the contact page to look better. 
Look at this:

Fix the styling on the contacts page

---

backend/internal/storage/postgres/schema/contact.go

fix contacts endpoint

---

frontend/src/app/(main)/layout.tsx
frontend/src/components/contacts/ContactDetailsContent.tsx
frontend/src/components/contacts/ContactTable.tsx
frontend/src/components/onboarding/login-form.tsx
frontend/src/components/transactions/ItemForm.tsx
frontend/src/components/transactions/LineItemTable.tsx
frontend/src/components/transactions/ModalDialog.tsx
frontend/src/components/ui/loading-spinner.tsx
frontend/src/components/user_profile/ProfileDropdown.tsx
frontend/src/context/ContactContext.tsx

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/234#issue-2978062613)
Added fancy loading spinners to everything
https://github.com/user-attachments/assets/2a016648-57c1-414f-8bdb-5324652ca657

loading spinners

---

frontend/src/app/(main)/transactions/page.tsx
frontend/src/components/dashboard/DatePicker.tsx
frontend/src/components/transactions/ContactFilter.tsx
frontend/src/components/transactions/ContactsFilterSelector.tsx
frontend/src/components/transactions/ContactsSelector.tsx
frontend/src/components/transactions/DatePicker.tsx
frontend/src/components/transactions/LineItemTable.tsx
frontend/src/components/transactions/LineItemTableFilters.tsx
frontend/src/components/transactions/PriceFilter.tsx

…/styling
[Link to Ticket](https://github.com/GenerateNU/arenius/issues/237)
Added clear and apply filters to each individual filter on the line item table. Also added some additional spacing and made the table headers taller as Amanda had requested. 
Also I made the existing "Clear Filters" button always be there, because I didn't like the way it looked how it appeared and shifted everything on the page down if it wasn't there before (when no filters were applied). But I can also easily revert this if design/others disagree. 

adding clear and apply filters to transaction page and fixing styling

---

frontend/src/middleware.ts

hopefully fix deployed, continuous loop with expired cookies

middleware fix

---

frontend/src/components/contacts/ContactDetailsContent.tsx
frontend/src/components/contacts/columns.tsx

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/238#issue-2978181299)
Added contact initials image to table
updated contact page with overview and notes and changes the numbers and made contact info only appear if it exists

Contact page edits

---

frontend/src/components/contacts/ContactDetailsColumns.tsx
frontend/src/components/contacts/ContactDetailsContent.tsx
frontend/src/components/contacts/ExportContactSummaryButton.tsx

Contact pageupdates

---

frontend/src/components/contacts/ContactDetailsContent.tsx
frontend/src/components/contacts/EditContactForm.tsx
frontend/src/components/contacts/EditContactModal.tsx
frontend/src/services/contacts.ts
frontend/src/types.ts

when a contact is edited using the modal and then we close the modal, we should update the page to reflect the edits we just made.

Update contact page after editing

---

backend/internal/storage/postgres/schema/line_item.go
frontend/src/lib/utils.ts

No More Dating Troubles 😊

---

frontend/src/components/contacts/columns.tsx
frontend/src/components/transactions/LineItemTable.tsx
frontend/src/components/transactions/ModalDialog.tsx
frontend/src/components/transactions/columns.tsx

bring chevron back

---

frontend/src/context/TransactionContext.tsx

[Link to Ticket](https://github.com/GenerateNU/arenius/issues/272#issue-2984037529)
three line fix! yay

filter applys to recommended
